all : context.c context2.c context3.c signal.c
		gcc -w -g context.c -o context
		gcc -w -g context2.c -o context2
		gcc -w -g context3.c -o context3
		gcc -w signal.c -o signal 

clean :
		rm context context2 context3 signal

